---
title: "Response overview"
output:
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kbtbr)
library(dplyr)

removeBaseUrl <- function(url){
  input_url <- gsub("https://kobo.correlaid.org/api/v2/", "", url)
  gsub("\\?format=json", "", input_url)
}
```


```{r list-assets}
base_url <- Sys.getenv("KBTBR_BASE_URL")
token <- Sys.getenv("KBTBR_TOKEN")

kobo <- Kobo$new(base_url, token)
assets <- kobo$get("assets/")$results
```

# Survey
```{r}
surveys <- assets %>% 
  filter(asset_type == "survey")

survey_test <- surveys[1, ]
surveyObject <- kobo$get(removeBaseUrl(survey_test$url))
str(surveyObject, max.level = 2)
```


```{r}
surveyObject$content
typeof(surveyObject$permissions)
```



# Block

# Question

# Template

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
